version: '2'
services:
    webserver:
        image: jasonkhan/dockerairflow:latest
        container_name: airflow-web
        volumes:
            - ./dags:/home/airflow/dags
        ports:
            - "8080:8080"
        entrypoint: /bin/sh -c "/home/airflow/init/webserver.sh"
