version: '2'
services:
    webserver:
        image: jasonkhan/dockerairflow:latest
        container_name: airflow-web
        volumes:
            - ./dags:/home/airflow/dags
            - ./init/webserver.sh:/usr/local/bin/webserver.sh
        ports:
            - "8080:8080"
        entrypoint: ./init/webserver.sh


    scheduler:
        image: jasonkhan/dockerairflow:latest
        container_name: airflow-scheduler
        depends_on:
            - webserver
        volumes:
            - ./dags:/home/airflow/dags
        entrypoint: ./init/scheduler.sh